# Generated by Django 5.2.10 on 2026-02-01 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.profile')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('RSD', 'Serbian dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar'), ('RUB', 'Russian ruble')], max_length=3)),
                ('to_currency', models.CharField(choices=[('RSD', 'Serbian dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar'), ('RUB', 'Russian ruble')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Amount in user`s base currency', max_digits=12)),
                ('currency', models.CharField(choices=[('RSD', 'Serbian dinar'), ('EUR', 'Euro'), ('USD', 'US Dollar'), ('RUB', 'Russian ruble')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('raw_text', models.TextField(blank=True, help_text='Original AI message')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.category')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='users.family')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.profile')),
            ],
        ),
    ]
