# Generated by Django 5.2.10 on 2026-02-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='currencyrate',
            index=models.Index(fields=['from_currency', 'to_currency', '-date'], name='transaction_from_cu_4c8542_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['profile', '-date'], name='transaction_profile_e013cb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['family', '-date'], name='transaction_family__c491af_idx'),
        ),
    ]
