# Generated by Django 5.2.10 on 2026-02-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_currencyrate_transaction_from_cu_4c8542_idx_and_more'),
        ('users', '0006_family_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='currencyrate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_category_per_user'),
        ),
        migrations.AddConstraint(
            model_name='currencyrate',
            constraint=models.UniqueConstraint(fields=('from_currency', 'to_currency', 'date'), name='unique_currency_rate_per_day'),
        ),
    ]
