# Generated by Django 5.2.10 on 2026-02-15 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_family',
            field=models.ForeignKey(blank=True, help_text='The family currently selected for recording expenses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_profiles', to='users.family'),
        ),
    ]
