# Generated by Django 5.2.10 on 2026-02-15 17:31

import apps.users.models.family
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_family_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='invite_code',
            field=models.CharField(default=apps.users.models.family.generate_invite_code, help_text='Secure code for joining the family', max_length=12, null=True, unique=True),
        ),
    ]
