# Generated by Django 5.2.10 on 2026-02-28 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_family_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the family', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_families', to='users.profile'),
        ),
    ]
